[WIP] User friendlier signup errors
m3o/services pull request #353
Opened 2020-09-24 13:58 UTC by crufter

2020-09-24 14:19 UTC, domwong commented on signup/handler/signup.go
> +		return merrors.Forbidden("signup.notallowed", "user %v has not been invited to sign up", req.Email)
We should probably change the error to something a bit nicer like "We're currently operating an invite only beta and this email address has not been invited"

2020-09-24 14:19 UTC, crufter commented on signup/handler/signup.go
> +		return merrors.Forbidden("signup.notallowed", "user %v has not been invited to sign up", req.Email)
I love that! :+1:

2020-09-28 08:20 UTC, asim commented on signup/handler/signup.go
> +		return merrors.Forbidden("signup.notallowed", "user %v has not been invited to sign up", req.Email)
Do not mention anything about beta. It's an invite only service. Beta is not a thing you put in messages.

2020-09-28 08:20 UTC, ben-toogood requested changes

2020-09-28 08:20 UTC, ben-toogood commented on signup/handler/signup.go
> +	notInvitedErroMsg = "We're currently operating an invite only beta and this email address has not been invited"
Typo Erro => Error

2020-09-28 08:20 UTC, ben-toogood commented on signup/handler/signup.go
> +		return merrors.Forbidden("signup.Verify.not_allowed", notInvitedErroMsg)
Can we now use _ here and instead format as `signup.Verify.NotAllowed`?

2020-09-28 08:20 UTC, ben-toogood commented on signup/handler/signup.go
> +		return merrors.Forbidden("signup.CompleteSignup.not_allowed", "Email '%v' has not been invited to sign up", req.Email)
Same as above

2020-09-28 08:36 UTC, asim commented on signup/handler/signup.go
> +	internalErrorMsg   = "Something went wrong during signup. Please try again a bit later. If the issue persists, let us know on Slack"
"An error occurred during signup. Contact #m3o-support at slack.m3o.com if the issue persists"

2020-09-28 08:37 UTC, asim commented on signup/handler/signup.go
> +	notInvitedErrorMsg = "We're currently operating an invite only beta and this email address has not been invited"
"You have not been invited to the service. Please request an invite on m3o.com"

2020-09-28 12:06 UTC, merged